### ISSUE TITLE
Error in documentation on python develop env

### ISSUE THREAD

**Issue by jorisvanzundert** [interedition/collatex#20]
Contributing.rst now says: 

$ mkvirtualenv collatex
$ cd collatex/
$ python setup.py develop

But I think it should be:

$ mkvirtualenv collatex
$ cd collatex/collatex-pythonport
$ python setup.py develop

Which means "4. Create a branch for local development:" should read "cd .." in line 1
(because one needs to check out the project in the main collatex directory) and "5." should start width "cd collatex-pythonport" again.

**Comment by djbpitt** [comment]
@jorisvanzundert Thank you for the correction! I've changed the `cd collatex/` line to ` cd collatex/collatex-pythonport`. It happened too late for today's release of version 2.2, but it will be in the next one.

With respect to the paragraph at the end, though, I think it should be possible to check out a branch from anywhere within the repo, and not only from the main directory. There is a risk of problems if you check out a branch from a subdirectory that has been deleted within the branch you're checking out, but that seems like a fringe situation. I'll close the issue, but please feel free to reopen it if there's something about the checkout directory that I've overlooked.
