### ISSUE TITLE
which version of java is required

### ISSUE THREAD

**Issue by maieul** [interedition/collatex#26]
Hi, I have tried a local version of `collatex-tools-1.7.0.jar` on my computer.

I obtained " Unsupported major.minor version 52.0".

So what is the minimal requirement? Should it be add on the website?

And also: I read you are doing a python version. Is both java version and python will be maintened, or only python.

**Comment by gremid** [comment]
Hi,

as per http://collatex.net/download/, JRE v8 is required.

Current development is taking place in the python version but both versions are maintained.

**Comment by maieul** [comment]
ouf, sorry, I was too speedy.

**Comment by maieul** [comment]
I have Java 8 mise à jour 66, but still this message.

**Comment by rhdekker** [comment]
Hi,

Like Gregor mentioned this error occurs when CollateX is run with a Java version lower than 8. Now since you assert to have Java 8 installed this raises more questions.
To help you out I need to know more information. Can you tell me which OS you are running? Linux, Windows or Mac OS X? What does the java --version command return in the command prompt or terminal window? Are you running the SDK or the JRE version of Java? The OpenJDK one or the one from Oracle?

Regards,
Ronald

**Comment by maieul** [comment]
Mac Os 10.8.5.

java --version return
> Unrecognized option: --version
> Could not create the Java virtual machine. 

I have reinstalled JRE from https://www.java.com/fr/download/mac_download.jsp but same problem

**Comment by tla** [comment]
There's a small bug in Ronald's instructions: it should be a single dash, not a double dash. Thus ought to look something like this:

    MacBook-Pro-2:~ tla$ java -version
    java version "1.8.0_45"
    Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
    Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

**Comment by maieul** [comment]
> java version "1.6.0_65"
> Java(TM) SE Runtime Environment (build 1.6.0_65-b14-462-11M4609)
> Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-462, mixed mode)


which is the way to update it ? I have download the .dmg file on the java website, run it� and nothing new

**Comment by rhdekker** [comment]
Did you follow all the steps in this guide?

https://www.java.com/fr/download/help/mac_install.xml

Ronald


On 14 Dec 2015, at 10:08, Maïeul Rouquette <notifications@github.com<mailto:notifications@github.com>> wrote:


> java version "1.6.0_65"
> Java(TM) SE Runtime Environment (build 1.6.0_65-b14-462-11M4609)
> Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-462, mixed mode)


which is the way to update it ? I have download the .dmg file on the java website, run it� and nothing new

**Comment by maieul** [comment]
yes I did.

I will ask tomorrow to the helpdesk of my university

**Comment by rhdekker** [comment]
Ok. Older versions of Mac OS X had their own distribution of Java supplied by Apple. Maybe that plays a role here. It could be that there are multiple versions of Java installed on your machine. But it is hard to say for sure from a distance. Hopefully your university can help you out.

Ronald

On 14 Dec 2015, at 13:21, Maïeul Rouquette <notifications@github.com<mailto:notifications@github.com>> wrote:

yes I did.

I will ask tomorrow to the helpdesk of my university

**Comment by maieul** [comment]
Ok, I found the good version of JDK, and it seems to be ok :-)
