### ISSUE TITLE
Colours in HTML

### ISSUE THREAD

**Issue by mhbeals** [interedition/collatex#36]
May be beneficial to have a different HTML2 colour scheme, such as Blue/Yellow to aid those with Red/Green colour-blindness

**Comment by rhdekker** [comment]
I agree, the current colours are just programmers art and were not intended to stay in the code for as long as they did. The color values have to provided in RGB values in hex. So dark red is FF0000 for example. I would need to find new corresponding color values.

**Comment by mhbeals** [comment]
FFFF00 (yellow) and 0000FF (blue)

**Comment by rhdekker** [comment]
Patch is included in CollateX Python.
