### ISSUE TITLE
Input encoding of known gaps

### ISSUE THREAD

**Issue by GermaineG** [interedition/collatex#39]
I want to use CollateX on pretty fragmentary text witnesses. In some cases I know about existing gaps and sometimes their length even, from the given data.
Is there a way to inform CollateX about such gaps? I am using a json input with tokens and their normalized forms atm.

**Comment by rhdekker** [comment]
Dear Germaine,

At the moment there is no such functionality in CollateX. You could try inserting unique tokens (for example xx) in the places in the witnesses where you know that there are gaps.
You might have to make them unique for each witnesses, for example by using x1 for gaps in witness 1 and x2 for gaps in witness 2 to make sure that the gaps do not get aligned.

Best,
Ronald


On 05 Nov 2016, at 16:57, GermaineG <notifications@github.com<mailto:notifications@github.com>> wrote:


I want to use CollateX on pretty fragmentary text witnesses. In some cases I know about existing gaps and sometimes their length even, from the given data.
Is there a way to inform CollateX about such gaps? I am using a json input with tokens and their normalized forms atm.
