### ISSUE TITLE
Homepage is offline

### ISSUE THREAD

**Issue by bencomp** [interedition/collatex#43]
The [CollateX website](http://collatex.net/) returns HTTP 404.

**Comment by rhdekker** [comment]
Thanks for your message. We are aware of the problem and are working on a solution.
In the meantime we have set up a temporary website at https://collatex.huygens.knaw.nl that you can use.

On 22 Feb 2017, at 09:53, bencomp <notifications@github.com<mailto:notifications@github.com>> wrote:


The CollateX website<http://collatex.net/> returns HTTP 404.

**Comment by rhdekker** [comment]
The problem has been solved. The website https://collatex.net is now back online.
