### ISSUE TITLE
TypeError OutEdgeDataView

### ISSUE THREAD

**Issue by bleekere** [interedition/collatex#45]
Hi,
When calling the collate() function I get an error message:
  File "/Users/ellibleeker/anaconda3/lib/python3.6/site-packages/collatex/core_classes.py", line 329, in join
    (_, join_candidate) = out_edges[0]
TypeError: 'OutEdgeDataView' object does not support indexing

Working with latest version (2.0) of NetworkX; this might be the problem?

**Comment by brambg** [comment]
Are you using Anaconda python?
https://www.anaconda.com/download/
I had that same error until early this way, and using anaconda python
solved it.

**Comment by bleekere** [comment]
The issue appears to be caused by NetworkX: I uninstalled version 2.0 and installed an older version (1.11). This solved the problem.
