### ISSUE TITLE
Error if segmentation used for example

### ISSUE THREAD

**Issue by catsmith** [interedition/collatex#53]
I am getting the following error in both the pypi and github version of the python-port when trying to run the example collation code. I am using Python3 and have not checked this in python2.  If segmentation is set to False in the collate() call then the collation completes as expected. I do not need to use the built in segmentation so this does not cause a problem for me but I thought it should be reported as it causes the example code to break.

**Error message below:**

/srv/itsee/django_project/collation/collatex/collatex-pythonport/collatex/core_functions.py in collate(collation, output, layout, segmentation, near_match, astar, detect_transpositions, debug_scores, properties_filter, indent, scheduler)
     71     # join parallel segments
     72     if segmentation:
---> 73         join(graph)
     74         ranking = VariantGraphRanking.of(graph)
     75     # check which output format is requested: graph or table

/srv/itsee/django_project/collation/collatex/collatex-pythonport/collatex/core_classes.py in join(graph)
    321         out_edges = graph.out_edges(vertex)
    322         if len(out_edges) is 1:
--> 323             (_, join_candidate) = out_edges[0]
    324             can_join = join_candidate != end and len(graph.in_edges(join_candidate)) == 1
    325             if can_join:

TypeError: 'OutEdgeDataView' object does not support indexing

**Comment by rhdekker** [comment]
Problem with newer version of CollateX:
AttributeError: 'DiGraph' object has no attribute 'edges_iter'

CollateX Python at the moment only works with networkx version 1.X.
Check the current version of networkx with 'pip show networkx'
If NetworkX version > 1.xx:
First uninstall the current networkx version by typing ‘pip uninstall networkx’ (without the quotes) and then install the working version by typing 'pip install -Iv networkx==1.11'without the qoutes.

**Comment by rhdekker** [comment]
This is fixed in the master branch. Fix still needs to be released.

**Comment by rhdekker** [comment]
New release is up now! 2.2. See https://pypi.org/project/collatex/
