### ISSUE TITLE
JSON to TEI

### ISSUE THREAD

**Issue by khayyak** [interedition/collatex#77]
Hello , can  use this tool to convert JSON file to type of XML(TEI) ?

**Comment by rhdekker** [comment]
Hi, only if you are looking to create a critical apparatus in TEI/XML.

**Comment by khayyak** [comment]
Thanks for responding , but can you explain me what you mean , because I only want to convert any kind of JSON data to XML file (TEI)

**Comment by rhdekker** [comment]
This tool can not convert any kind of JSON data to TEI/XML. It can only convert a specific form of JSON data, being arrays of tokens, to a specific form of TEI/XML, being a critical apparatus.
