### ISSUE TITLE
Can the latest Python 3.10 fix be pushed to PyPi?

### ISSUE THREAD

**Issue by CKrawczyk** [interedition/collatex#89]
I am currently updating one of my Python packages that uses `collatex` to be compatible with Python 3.10 and 3.11, I see https://github.com/interedition/collatex/pull/83 has fixed the import error I am running across.  Are there plans for this change to be released to PyPi anytime soon?  I would much rather just bump the version number of the dependency in my package rather than set it to install from a specific commit on GitHub.

**Comment by rhdekker** [comment]
I am looking into it. Need some assistance from the organisation behind PyPi.org and am unsure how long that is going to take.

**Comment by CKrawczyk** [comment]
Is there any progress on this? This issue prevents me from pushing my package that uses collatex as a dependence to PyPi.org (PyPi does not allow dependencies that link to Git Hub branches).

**Comment by rhdekker** [comment]
Alright, we made a release. I was able to install it locally by fetching from Pypi using pip. Can you try and report back whether it works for you?

**Comment by CKrawczyk** [comment]
Great everything works, thanks.
