### ISSUE TITLE
demo service seems down (as of 2024-02-9 15:40 EST)

### ISSUE THREAD

**Issue by jeffreycwitt** [interedition/collatex#93]
Just noting that the demo site and collax api seems down at the moment. (2024-02-9 15:40 EST)

<img width="528" alt="image" src="https://github.com/interedition/collatex/assets/1146685/4dde7bb7-f9e3-4f34-8817-ca254cc71437">

I enjoy being able to use the service and just wanted to see if it could be restored. 

(I totally understand if it's not possible)

**Comment by djbpitt** [comment]
@jeffreycwitt Thanks for reporting the problem, which apparently happened during server maintenance. @rhdekker reported it to the system administrators, so it’s in the queue, although we don’t have an estimate yet of when that will happen. Apologies for the inconvenience!

**Comment by rhdekker** [comment]
@jeffreycwitt @djbpitt The issue has been resolved. It was caused by expired SSL certificates.

**Comment by jeffreycwitt** [comment]
Awesome! Thanks so much!
